<!-- job/timeline.phtml -->

<?php 

echo "<script type='text/javascript'>";
echo "var jsonurl = '". $this->baseUrl ."/job/timelinejson';";
echo "var jdate = '" . $this->datetimeline . "';";
echo "</script>";

?>

<script type="text/javascript">

	$(function() {

		$( "#datepicker" ).datepicker();
		$( "#datepicker" ).datepicker({ gotoCurrent: true });
		$( "#datepicker" ).datepicker("option", "dateFormat", "yy-mm-dd");
		$( ".selector" ).datepicker( "option", "gotoCurrent", true );
		$( "input[type=submit]" ).button();
		$( "#accordion" ).accordion();
		$( "#from" ).datepicker();
		$( "#from" ).datepicker("option", "dateFormat", "yy-mm-dd");
		$( "#to" ).datepicker();
		$( "#to" ).datepicker("option", "dateFormat", "yy-mm-dd");
		
	});
	
	$(document).ready(function () {
		loadTimeline(jsonurl, jdate);
	});
	
</script>

<!-- NEW TIMELINE START -->

<div class="ui-widget-content" style="width: 1024px; padding: 10px;">

      <?php echo "<h3 class='ui-widget-header' style='padding: 10px;'>" . $this->escape($this->translate->_($this->title)) . "</h3>"; ?>
      
      <div id="accordion">
      
      <h3><a href="#"><?php echo $this->translate->_("Date"); ?></a></h3>
      <div>
      <form action="<?php echo $this->baseUrl; ?>/job/tdate" method="POST">
      <p>
      <div id="dpick"><?php print $this->translate->_("Date"); ?><input type="text" id="datepicker" name="datepicker" title="<?php echo $this->translate->_("Please enter a date"); ?>" /></div>
      </p>
      <input id="showTimeline" type="submit" value="<?php print $this->translate->_("Show Timeline"); ?>" />
      </form>
      </div>
      
      <h3><a href="#"><?php echo $this->translate->_("Period of time"); ?></a></h3>
      <div>
      <form action="<?php echo $this->baseUrl; ?>/job/rdate" method="POST">
      <p>
      <div id="rpick"><?php print $this->translate->_('From'); ?><input type="text" id="from" name="from" title="<?php echo $this->translate->_("Please enter a date"); ?>" />
      <?php print $this->translate->_('to'); ?><input type="text" id="to" name="to" title="<?php echo $this->translate->_("Please enter a date"); ?>" /></div>
      </p> 
      <input id="showTimeline" type="submit" value="<?php print $this->translate->_("Show Timeline"); ?>" />
      </form>
      </div>
     
      </div>

</div>

<p>
<?php

	if( empty( $this->result_error) ) {
		echo '<div class="ui-widget-content" style="width: 1024px; padding: 10px; text-align: center;">';
		echo '<div id="jobtimeline" class="ui-widget-content" style="z-index: 1; width: 1024px; height: 350px; border: 1px solid #aaa; font-size: 12px;"></div>';
		echo '</div>';
	}
	else {
		echo '<div class="ui-widget" style="float: left;">';
		echo '<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">';
		echo '<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>';
		echo '<strong>' . $this->result_error . '</strong></p>';
		echo '</div>';
		echo '</div>';
	}

?>
</p>

<p style="clear: both;">&nbsp;</p>

<!-- NEW TIMELINE END -->
